/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.recargas;

import com.mycompany.Persistencia.CelularJpaController;
import com.mycompany.Persistencia.RecargasJpaController;
import com.mycompany.Clases.Recargas;
import com.mycompany.Clases.Celular;
import com.mycompany.Persistencia.CelularJpaController;
import com.mycompany.Persistencia.RecargasJpaController;
import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class Recargar extends javax.swing.JFrame {

    /**
     * Creates new form Recargar
     */
    public Recargar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonValidarNumero = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextValidarNumero = new javax.swing.JTextField();
        jTextRecargaValor = new javax.swing.JTextField();
        jButtonRecarga = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonValidarNumero.setText("VALIDAR");
        jButtonValidarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarNumeroActionPerformed(evt);
            }
        });

        jLabel11.setText("Numero:");

        jLabel13.setText("Valor:");

        jButtonRecarga.setBackground(new java.awt.Color(204, 255, 255));
        jButtonRecarga.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 24)); // NOI18N
        jButtonRecarga.setForeground(new java.awt.Color(102, 0, 102));
        jButtonRecarga.setText("Recargar");
        jButtonRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecargaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Recargas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextValidarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButtonValidarNumero))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonRecarga)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextRecargaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(94, 94, 94)))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(163, 163, 163))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextValidarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonValidarNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextRecargaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButtonRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarNumeroActionPerformed
        // TODO add your handling code here:
        try {
            String numeroIngresado = jTextValidarNumero.getText();

            if (numeroIngresado.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un número.");
                return;
            }

            CelularJpaController celularController = new CelularJpaController();
            Celular celular = celularController.buscarCelularPorNumero(numeroIngresado);

            if (celular != null) {
                JOptionPane.showMessageDialog(this, "El número se encuentra registrado!!!");
            } else {
                JOptionPane.showMessageDialog(this, "El número no está registrado.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al validar el número: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonValidarNumeroActionPerformed

    private void jButtonRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecargaActionPerformed
        

        try {
        String numero = jTextValidarNumero.getText();  // Suponiendo que el número se ingresa en un JTextField llamado txtNumero
        double valorRecarga = Double.parseDouble(jTextRecargaValor.getText()); // Suponiendo un JTextField txtValor

        // Buscar celular en la base de datos
        CelularJpaController celularController = new CelularJpaController();
        Celular celular = celularController.buscarCelularPorNumero(numero); // Este método debe existir

        if (celular == null) {
            JOptionPane.showMessageDialog(this, "Celular no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calcular nuevos valores
        double nuevoSaldo = celular.getSaldo() + valorRecarga;
        double nuevosMegas = celular.getMegas() + (valorRecarga * 10); // Ejemplo: 10 MB por peso recargado

        // Crear la recarga
        Recargas recarga = new Recargas();
        recarga.setValor(valorRecarga);
        recarga.setSaldo(nuevoSaldo);
        recarga.setMegas(nuevosMegas);
        recarga.setCelular(celular);

        // Guardar recarga en la base de datos
        RecargasJpaController recargaController = new RecargasJpaController();
        recargaController.create(recarga);

        // Actualizar saldo y megas del celular
        celular.setSaldo(nuevoSaldo);
        celular.setMegas(nuevosMegas);
        celularController.edit(celular);

        JOptionPane.showMessageDialog(this, "Recarga realizada con éxito.");
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al realizar la recarga: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }


    }//GEN-LAST:event_jButtonRecargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recargar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRecarga;
    private javax.swing.JButton jButtonValidarNumero;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JTextField jTextRecargaValor;
    private javax.swing.JTextField jTextValidarNumero;
    // End of variables declaration//GEN-END:variables
}
